dist: trusty
language: node_js
node_js:
  - "7.4.0"
branches:
  only:
  - master
  - feature/coveralls-integration
  - develop
  - release
install:
  - npm install -g npm@latest
  - npm install
after_success: npm run coverage
